### ISSUE TITLE
non support -v4 version

### ISSUE THREAD

**Issue by jjhesk** [DMCApps/NavigationFragment#1]
Does it have non-v4-support version of fragment?

**Comment by DMCApps** [comment]
After doing some research. I was using the support library in order to maximize the amount of devices that I can support. Looks like the Fragment class was released in API 11 (3.0 Honeycomb) and based on the usages from google http://developer.android.com/about/dashboards/index.html. Majority of devices accessing the PlayStore are above 3.0 (over 95%). 

I can't see why I would need to keep the support library in there. I'll look at converting it to a non-support library and updating the ReadMe over the weekend. For the time being you can just implement the library with the support in your gradle file and I'll post here once I have updated the Library.

May I ask why you need a version that is non-v4-support? There is no reason not to include and use the support library. It allows you to encompass all devices using the app store and it works the same across the different API version, since Google has made the Fragment class backwards compatible through this library.

**Comment by DMCApps** [comment]
As I was updating the Library I realized that I use the Child Fragment Manager. I need to use the support library in order to use this manager in earlier API levels. I will not be taking out the support library as that will force me to use API 17 (4.2 losing additional devices) as the min SDK, so that I can use the child fragment manager. Since the Child Fragment Manager is the key to how I do the navigation, I will not be taking out the support library.

I apologize for the inconvenience, please add the support library to your project if you would like to use the library.

**Comment by jjhesk** [comment]
thats fine i understand it now. I will just have to switch all other components into v4 base and thats alot of works to convert them. if it is possible, you dont need to take out the v4 lib and just issue another library that is non-v4 base. just like what he did in the [library](https://github.com/ogaclejapan/SmartTabLayout) and you will able to compensate all the non-v4 components.

**Comment by DMCApps** [comment]
Ah I see. At this point in time. I need to do some code clean up to make that part possible. As it stands I will leave the library as support only and as I clean up the code and improve the style I'll look into adding a non support Fragment Version. Thanks for the feedback!

**Comment by jjhesk** [comment]
I am so excited to see ur progress for this library. I think it should be included in the google android sdk library at the end. #

**Comment by DMCApps** [comment]
version 1.0.0 has just been released and has a non-support version! Enjoy!

**Comment by jjhesk** [comment]
@DMCApps congrats!
