### ISSUE TITLE
backward supports for memory leak issue on android 4.0.0

### ISSUE THREAD

**Issue by jjhesk** [DMCApps/NavigationFragment#20]
since are issues existed in the version 4.0+. would you help me to adding support for the leak issue before lilipop? The code are listed here @DMCApps @DMan654  
[https://gist.github.com/jjhesk/f1d1263852d48f06ed3e072a32247bb6](https://gist.github.com/jjhesk/f1d1263852d48f06ed3e072a32247bb6)

**Comment by DMCApps** [comment]
@jjhesk I apologize for the late response, I'd be more than happy to implement this, I'm just not sure what I need to do though? 

Is it just the suggested edit that @jackcsk has added or is there more that I am missing?

Thanks

**Comment by DMCApps** [comment]
I already have an implementation of your NestingFragment in my implementation as my RetainedChildFragmentManagerFragment (https://github.com/DMCApps/NavigationFragment/blob/master/navigation-fragment/src/main/java/com/dmcapps/navigationfragment/helper/RetainedChildFragmentManagerFragment.java) 

If you give me some guidance on what I need to change I would happily do that for you!

**Comment by DMCApps** [comment]
Hello @jjhesk,

I attempted to implement this update and when I did I ran into the `mNextAnim null` issue that you have expressed a few times. I can't implement this change because we are using the support fragment. The support fragment (no matter the OS version of the device) is always changing it's `ChildFragmentManager` and hence adding in the if statement as suggested by @jackcsk causes issues with the support child fragment manager.
