### ISSUE TITLE
fragment on pause will crash

### ISSUE THREAD

**Issue by jjhesk** [DMCApps/NavigationFragment#4]
tried to open an new intent but it crash.. same from #2

**Comment by DMCApps** [comment]
Fixed in 0.0.4.2

Please let me know if it persists after updating

**Comment by DMCApps** [comment]
Check 0.0.4.2 

Both the Master Detail and the Single Stack manager are fully Serializable.

**Comment by DMCApps** [comment]
Hey jjhesk,

So this issue seems to have been bigger than I expected. As I was using the Manager, I ran into this "NotSerializableException" on my home button press and any time I presented an activity. I was expecting that it was because my class was not Serializable hence I removed anything that wasn't serializable from my class and it was working. 

The issue continues to happen though anytime you have a fragment with a property in it that is not serializable in it. So I have made a fix for this and it can be found as 0.0.5. All the methods for using the Manager remain the same so you should be good to go once you upgrade to 0.0.5!

Thanks for your continued use and pantience.

**Comment by jjhesk** [comment]
Thank you so much for this fix. As I have bumped into the errors or crashes that is not occurred in my code lines i had no idea and having a big headache in dealing this kind of things. I couldnt start digging ur code from anywhere.  If u have the time, would u able to produce a map or a chart to explain how this library works in the scope of its lifecycle and remaining its fragments inside the fragment manager. 

A big thumbs up for your effort.

**Comment by DMCApps** [comment]
Just to clarify, this issue is cleaned up?

I can look into adding something like this to the library in the future. What in particular would you like to see. The ReadMe is quite detailed in how to use the manager, so I'm not 100% sure what to put on this map/chart.
