### ISSUE TITLE
animation overriding with xml stylings

### ISSUE THREAD

**Issue by jjhesk** [DMCApps/NavigationFragment#7]
If you let me to adding PR to your lib I will like to add default animation in/out for presenting and dismissing on the navigationfragment so that it doesnt need to explicitly call out at using the methos presenting and dismissing fragment. put that on the check box for later development as this is not important. 
- [x] assign default animation by using style xml.

**Comment by DMCApps** [comment]
I'm not quite sure what you are asking or what you are experiencing? 

Currently if you call `presentFragment(INavigationFragment fragment)` or `dismissFragment()` from any NavigationFragment (or NavigationListFragment) within a NavigationManagerFragment there is a default animation performed. 

The default animations are defined as:
presenting: slide in from right and slide out to left
dismissing: slide out to right and slide in from left

There are also override methods which you can pass in animations from your resources instead of the default animations. 

There are also methods for overriding the default animations defined as:
`presentFragment(INavigationFragment fragment, int animIn, int animOut)`
`dismissFragment(int animIn, int animOut)`

**Comment by jjhesk** [comment]
I am refering to the xml resource for style configurations.  there could store some style elements in the resource xml so that could override the default animation from not using the explicit inputs. You can get some ideas from [here](http://stackoverflow.com/questions/2625812/start-activity-with-an-animation).  Some implementations are like this 

``` xml
<!-- the animations must have been defined in your "anim" folder, of course -->
<style name="Animation.MyAwesomeAnimation" parent="android:style/Animation.Activity">
    <item name="android:activityOpenEnterAnimation">@anim/myawesomeanimation_enter</item>
    <item name="android:activityOpenExitAnimation">@anim/hold_long</item>
    <item name="android:activityCloseEnterAnimation">@anim/hold_long</item>
    <item name="android:activityCloseExitAnimation">@anim/myawesomeanimation_exit</item>
</style>
```

**Comment by DMCApps** [comment]
Hey jj,

I was doing some code refactoring tonight and decided to add this in. Although I decided to not go through using the styles.xml, instead I have added two methods on the NavigationManagerFragment that you can set when you create the manager initially. I don't want to affect the default transitions that will occur when you don't use the manager and hence that is why I decided to use methods on the manage instead.

```
// From the Override Default Animations Example.

SingleStackNavigationManagerFragment navManager = SingleStackNavigationManagerFragment.newInstance(SampleFragment.newInstance("Root Fragment in the Stack", 0));

navManager.setDefaultPresentAnimations(R.anim.slide_in_from_bottom, R.anim.slide_out_to_top);
navManager.setDefaultDismissAnimations(R.anim.slide_in_from_top, R.anim.slide_out_to_bottom);

// Now any Fragments presented from this manager will use your defined animations instead! You can still decide to override them on an individual present/dismiss bases as well!

addFragment(navManager);
```

I have added a tag to version 0.0.5 incase there are any bugs that creep up with the code refactoring. I did change around quite a bit so that the Manager is more modular on the inside and I plan to do more as well. You won't notice any changes to how it functions or how to use it though so please continue as you are using it now!

Please check out the example in 0.1.1 to see how to set the default animations! Update your version to 0.1.1 if you'd like to start taking advantage of the refactor and the new default animation settings!

**Comment by jjhesk** [comment]
Thanks for the quick works. I hope it could be stable from this animation implementation. I will let u know if i get encountered in any crashes while working with another modules.
